version: '3.8'

services:
  frontend:
    build:
      context: ./fe-digg
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - digg-network

  backend:
    build:
      context: ./be-digg
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - digg-network

networks:
  digg-network:
    driver: bridge