import { User } from "./interfaces/User";

const database: User[] = [
  { name: "John Doe", email: "john.doe@email.com", phoneNumber: "070-123456", address: "Street 1" },
  { name: "Jane Smith", email: "jane.smith@email.com", phoneNumber: "070-654321", address: "Street 2" },
  { name: "Alice Johnson", email: "alice.johnson@email.com", phoneNumber: "070-223344", address: "Street 3" },
  { name: "Bob Brown", email: "bob.brown@email.com", phoneNumber: "070-334455", address: "Street 4" },
  { name: "Charlie Black", email: "charlie.black@email.com", phoneNumber: "070-556677", address: "Street 5" },
  { name: "Diana White", email: "diana.white@email.com", phoneNumber: "070-778899", address: "Street 6" },
  { name: "Eva Green", email: "eva.green@email.com", phoneNumber: "070-889900", address: "Street 7" },
  { name: "Frank Blue", email: "frank.blue@email.com", phoneNumber: "070-990011", address: "Street 8" },
  { name: "Grace Pink", email: "grace.pink@email.com", phoneNumber: "070-001122", address: "Street 9" },
  { name: "Hank Gray", email: "hank.gray@email.com", phoneNumber: "070-223355", address: "Street 10" },
  { name: "Ivy Red", email: "ivy.red@email.com", phoneNumber: "070-445566", address: "Street 11" },
  { name: "Jack Gold", email: "jack.gold@email.com", phoneNumber: "070-667788", address: "Street 12" },
  { name: "Kate Silver", email: "kate.silver@email.com", phoneNumber: "070-889911", address: "Street 13" },
  { name: "Leo Copper", email: "leo.copper@email.com", phoneNumber: "070-112233", address: "Street 14" },
  { name: "Mia Zinc", email: "mia.zinc@email.com", phoneNumber: "070-334466", address: "Street 15" },
  { name: "Nina Steel", email: "nina.steel@email.com", phoneNumber: "070-556677", address: "Street 16" },
  { name: "Oscar Iron", email: "oscar.iron@email.com", phoneNumber: "070-778899", address: "Street 17" },
  { name: "Paula Lead", email: "paula.lead@email.com", phoneNumber: "070-889900", address: "Street 18" },
  { name: "Quincy Wood", email: "quincy.wood@email.com", phoneNumber: "070-990011", address: "Street 19" },
  { name: "Rachel Stone", email: "rachel.stone@email.com", phoneNumber: "070-001122", address: "Street 20" },
  { name: "Sam Flint", email: "sam.flint@email.com", phoneNumber: "070-223344", address: "Street 21" },
  { name: "Tina Clay", email: "tina.clay@email.com", phoneNumber: "070-334455", address: "Street 22" },
  { name: "Uma Ice", email: "uma.ice@email.com", phoneNumber: "070-445566", address: "Street 23" },
  { name: "Victor Fire", email: "victor.fire@email.com", phoneNumber: "070-556677", address: "Street 24" },
  { name: "Wendy Water", email: "wendy.water@email.com", phoneNumber: "070-667788", address: "Street 25" },
  { name: "Xander Earth", email: "xander.earth@email.com", phoneNumber: "070-778899", address: "Street 26" },
  { name: "Yara Sky", email: "yara.sky@email.com", phoneNumber: "070-889900", address: "Street 27" },
  { name: "Zane Star", email: "zane.star@email.com", phoneNumber: "070-990011", address: "Street 28" },
  { name: "Andy Moon", email: "andy.moon@email.com", phoneNumber: "070-001122", address: "Street 29" },
  { name: "Betty Sun", email: "betty.sun@email.com", phoneNumber: "070-223344", address: "Street 30" },
];
export default database;
